# Generated by Django 6.0.2 on 2026-03-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_deal_custom_fields_lead_custom_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('PROSPECTING', 'Prospecting'), ('QUALIFICATION', 'Qualification'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSING', 'Closing')], default='PROSPECTING', max_length=20),
        ),
    ]
