# Generated by Django 6.0.3 on 2026-03-16 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edge_id", models.CharField(max_length=100)),
                ("source_node", models.CharField(max_length=100)),
                ("target_node", models.CharField(max_length=100)),
                (
                    "source_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "target_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="nodes.workflow",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkflowNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=100)),
                ("type", models.CharField(default="default", max_length=50)),
                ("position_x", models.FloatField()),
                ("position_y", models.FloatField()),
                ("data", models.JSONField(default=dict)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="nodes.workflow",
                    ),
                ),
            ],
        ),
    ]
