# Generated by Django 6.0.3 on 2026-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflow",
            name="viewport",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
