# Generated by Django 6.0.3 on 2026-03-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0002_workflow_viewport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflow",
            name="viewport",
        ),
    ]
